// <auto-generated />
namespace OrangeBricks.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Viewingentityandrelationshiptoproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Viewingentityandrelationshiptoproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201702121103258_Viewing entity and relationship to property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
